baseURL = "https://www.ohanabuilds.org/"
languageCode = "en-us"
title = "Ohana Builds"
enableGitInfo = true

disableKinds = ["taxonomy", "term"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params.build]
version = "0.1.0"
channel = "ohanabuilds"
git = "b9972c9"

[params]
  googleAnalyticsID = "G-BCMP0SN4D7"

enableRobotsTXT = true

[sitemap]
  filename = "sitemap.xml"
  changefreq = "weekly"
  priority = 0.5